Here are a few examples of replacing loops with native numpy functions. This is often clearer (directly reflecting the formulae we're trying to implement) and often much faster to run.

In [2]:
import numpy as np

In [3]:
np.set_printoptions(precision=2)

In [4]:
b = np.random.randn(2,3)
b

array([[-1.67, -1.63,  1.57],
       [ 2.48,  0.82, -1.16]])

Let's calculate

$a_{i} = \Sigma_{j} b_{ij}$

In [5]:
b.shape

(2, 3)

In [6]:
# Using loops
a = np.zeros(2)
for i in range(b.shape[0]):
    for j in range(b.shape[1]): 
        a[i] += b[i,j]
print(a)

[-1.72  2.14]


In [7]:
# Using numpy functions 
a = b.sum(axis=1)
print(a)

[-1.72  2.14]


What if we'd instead wanted

$a_{i} = \Sigma_{j} b_{ji}$ ?

We summed over `axis=1`, which is like summing the `j` indices for `b[i,j]`. We can sum over the first index instead with `b.sum(axis=0)`. Note that if you just write `b.sum()`, numpy will sum over *all* indices - this is a different default behaviour to Pandas' `sum()` method.

In [8]:
b.sum(axis=0)

array([ 0.82, -0.81,  0.41])

Let's calculate a dot product, which means element-wise multiplication of two arrays, and then summing the result:

$a = \Sigma_i b_{i} c_{i}$

In [18]:
b = np.random.randn(3)
c = np.random.randn(3)
print (b,c)

[-0.21  0.    1.02] [ 0.26 -0.62  1.26]


In [19]:
# Using loops
a = 0
for i in range(len(b)):
    a += b[i] * c[i]
print(a)

1.22139377366


In [22]:
# Using numpy
a = (b * c).sum()

# This is the same as the more explicit
product = b * c
a = product.sum()

print(a)

# OR we could use the dot product function, np.dot(b,c)


1.22139377366


Let's do matrix multiplication. This is defined as

$a_{ij} = \Sigma_u b_{iu} c_{uj}$

In [29]:
# Here i runs from 0..2, u runs from 0..1, and j runs from 0..2
b = np.random.randn(3,2)
c = np.random.randn(2,3)
print(b)
print(c)

[[ 0.6   0.64]
 [ 0.43 -0.27]
 [-0.2  -0.69]]
[[ 1.67  0.06 -0.3 ]
 [ 1.47 -0.4   1.55]]


In [31]:
# Using loops
# This only works correctly if b.shape[1] == c.shape[0]
a = np.zeros((b.shape[0],c.shape[1]))
for i in range(b.shape[0]):
    for j in range(c.shape[1]):
        for u in range(b.shape[1]):
            a[i,j] += b[i,u] * c[u,j]
print(a)

[[ 1.95 -0.22  0.81]
 [ 0.33  0.13 -0.54]
 [-1.34  0.26 -1.01]]


In [32]:
# Using numpy's matrix multiplication function
a = np.matmul(b,c)
print(a)

[[ 1.95 -0.22  0.81]
 [ 0.33  0.13 -0.54]
 [-1.34  0.26 -1.01]]


Let's calculate an "outer product", i.e. constructing a matrix by multiplying two vectors:

$a_{ij} = b_i c_j$

In [20]:
b = np.array([1, 2])  # nice round numbers to make this easier to see
c = np.random.randn(3)
print (b,c)

[1 2] [ 2.38 -0.57 -1.72]


In [21]:
# Using loops
a = np.zeros((len(b), len(c)))
for i in range(len(b)):
    for j in range(len(c)):
        a[i,j] = b[i] * c[j]
print(a)

[[ 2.38 -0.57 -1.72]
 [ 4.76 -1.14 -3.44]]


In [22]:
# Using numpy
# This is more advanced, and you probably won't need it directly in this course
# Both b and c are 1D, and we want a 2D result. So we need to switch either
# b or c to lie along the second dimension before we multiply
a = b[:,np.newaxis] * c
print(a)

[[ 2.38 -0.57 -1.72]
 [ 4.76 -1.14 -3.44]]


In [23]:
# This is what we did - turned b into a 'vertical' vector while c was 'horizontal'
b[:,np.newaxis]

array([[1],
       [2]])