Here are a few examples of replacing loops with native numpy functions. This is often clearer (directly reflecting the formulae we're trying to implement) and often much faster to run.

In [2]:
import numpy as np

In [11]:
b = np.random.randint(1,10,size=(2,3))
b

array([[8, 5, 1],
       [7, 5, 3]])

Let's calculate

$a_{i} = \Sigma_{j} b_{ij}$

In [12]:
b.shape

(2, 3)

In [13]:
# Using loops
a = np.zeros(2)
for i in range(b.shape[0]):
    for j in range(b.shape[1]): 
        a[i] += b[i,j]
print(a)

[ 14.  15.]


In [14]:
# Using numpy functions 
a = b.sum(axis=1)
print(a)

[14 15]


What if we'd instead wanted

$a_{i} = \Sigma_{j} b_{ji}$ ?

We summed over `axis=1`, which is like summing the `j` indices for `b[i,j]`. We can sum over the first index instead with `b.sum(axis=0)`. Note that if you just write `b.sum()`, numpy will sum over *all* indices - this is a different default behaviour to Pandas' `sum()` method.

In [15]:
b.sum(axis=0)

array([15, 10,  4])

Let's calculate a dot product, which means element-wise multiplication of two arrays, and then summing the result:

$a = \Sigma_i b_{i} c_{i}$

In [16]:
b = np.random.randint(1,10,size=(3))
c = np.random.randint(1,10,size=(3))
print (b,c)

[7 5 9] [8 1 4]


In [17]:
# Using loops
a = 0
for i in range(len(b)):
    a += b[i] * c[i]
print(a)

97


In [18]:
# Using numpy
a = (b * c).sum()

# This is the same as the more explicit
product = b * c
a = product.sum()

print(a)

# OR we could use the dot product function, np.dot(b,c)


97


Let's do matrix multiplication. This is defined as

$a_{ij} = \Sigma_u b_{iu} c_{uj}$

In [19]:
# Here i runs from 0..2, u runs from 0..1, and j runs from 0..2
b = np.random.randint(1,10,size=(3,2))
c = np.random.randint(1,10,size=(2,3))
print(b)
print(c)

[[1 3]
 [9 1]
 [2 5]]
[[6 7 9]
 [2 9 9]]


In [20]:
# Using loops
# This only works correctly if b.shape[1] == c.shape[0]
a = np.zeros((b.shape[0],c.shape[1]))
for i in range(b.shape[0]):
    for j in range(c.shape[1]):
        for u in range(b.shape[1]):
            a[i,j] += b[i,u] * c[u,j]
print(a)

[[ 12.  34.  36.]
 [ 56.  72.  90.]
 [ 22.  59.  63.]]


In [22]:
# Using numpy's matrix multiplication function
a = np.matmul(b,c)
print(a)

[[12 34 36]
 [56 72 90]
 [22 59 63]]


Let's calculate an "outer product", i.e. constructing a matrix by multiplying two vectors:

$a_{ij} = b_i c_j$

In [25]:
b = np.array([1, 2])  # nice small round numbers to make this easier to see
c = np.random.randint(1,10,size=(3))
print (b,c)

[1 2] [1 4 5]


In [26]:
# Using loops
a = np.zeros((len(b), len(c)))
for i in range(len(b)):
    for j in range(len(c)):
        a[i,j] = b[i] * c[j]
print(a)

[[  1.   4.   5.]
 [  2.   8.  10.]]


In [27]:
# Using numpy
# This is more advanced, and you probably won't need it directly in this course
# Both b and c are 1D, and we want a 2D result. So we need to switch either
# b or c to lie along the second dimension before we multiply
a = b[:,np.newaxis] * c
print(a)

[[ 1  4  5]
 [ 2  8 10]]


In [28]:
# This is what we did - turned b into a 'vertical' vector while c was 'horizontal'
b[:,np.newaxis]

array([[1],
       [2]])